### ISSUE TITLE
Project doesn't build with com.github.eirslett frontend-maven-plugin version 1.4

### ISSUE THREAD

**Issue by midryndhil** [spring-petclinic/spring-petclinic-angular1#10]
The version of the plugin 

```
<plugin>
<groupId>com.github.eirslett</groupId>
<artifactId>frontend-maven-plugin</artifactId>
</plugin>
```

is not set into the pom.xml of the client project.

So the last version (1.4) is used during the build and the build doesn't work anymore.

```
[INFO] --- frontend-maven-plugin:1.4:gulp (gulp build) @ spring-petclinic-client ---
[INFO] Running 'gulp ' in /Users/francois/Travail/kbl/tools/intellij/code/spring-petclinic-angular1/spring-petclinic-client
[ERROR] module.js:327
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module '/Users/francois/Travail/kbl/tools/intellij/code/spring-petclinic-angular1/spring-petclinic-client/target/node_modules/gulp/bin/gulp'
[ERROR]     at Function.Module._resolveFilename (module.js:325:15)
[ERROR]     at Function.Module._load (module.js:276:25)
[ERROR]     at Function.Module.runMain (module.js:441:10)
[ERROR]     at startup (node.js:139:18)
[ERROR]     at node.js:974:3
[INFO] -----------------------

[INFO] Spring Petclinic :: AngularJS Client ............... FAILURE [ 10.551 s]
[INFO] Spring Petclinic :: Spring MVC REST server ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.423 s
[INFO] Finished at: 2017-04-11T09:35:27+02:00
[INFO] Final Memory: 18M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:gulp (gulp build) on project spring-petclinic-client: Failed to run task: 'gulp ' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

Set the version to 1.3 fix the build for now.

https://github.com/eirslett/frontend-maven-plugin/issues/586

Regards,

**Comment by arey** [comment]
Thanks @midryndhil. By waiting the patch, I will downgrade to the 1.3 version.

**Comment by buennodelavega** [comment]
@arey is it solve in 1.5?

**Comment by arey** [comment]
Issue not solve in the 1.5 version
